[tox]
envlist = py311, py312, py313, py314, pypy311, lint, docs
isolated_build = true
requires = tox-uv

[testenv]
extras = dev
commands = pytest {posargs}

[testenv:lint]
extras = dev
commands = ruff check src tests

[testenv:benchmark]
extras = dev
commands = pytest -m benchmark {posargs}

[testenv:docs]
extras = docs
commands = mkdocs build --strict
