[tox]
envlist = py311, py312, py313, py314, pypy311, lint
isolated_build = true
requires = tox-uv

[testenv]
extras = dev
commands = pytest {posargs}

[testenv:lint]
extras = dev
commands = ruff check src tests
